baseURL = "http://perdrisat.com/"
languageCode = "en-us"
title = "Simon Perdrisat"

canonifyurls  = true
theme = "simplehugo"

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

[Author]
  name = "Simon Perdrisat"
  email = "perdrisat@gmail.com"
  gitlab = "gagarine__"
  github = "gagarine"
  twitter = "SimonPerdrisat"
  linkedin = "username"


  # Menu
[menu]
  [[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://github.com/gagarine"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "https://twitter.com/gagarine__"
    name = "Twitter"
    weight = 2
  [[menu.footer]]
    url = "https://www.linkedin.com/in/simonperdrisat/"
    name = "Linkedin"
    weight = 3
