baseurl = "http://perdrisat.com"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Simon Perdrisat"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "simplehugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
pygmentsoptions = "linenos=table"
pygmentsStyle = "vs"

#disqusShortname = ""
#googleAnalytics = ""



[Params]
  subtitle = "this and that"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = false
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[Author]
  name = "Simon Perdrisat"
  email = "perdrisat@gmail.com"
  gitlab = "gagarine"
  github = "gagarine"
  twitter = "gagarine"
  linkedin = "username"


# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
[menu]
  [[menu.main]]
    url = "/contact/"
    name = "contact"
    weight = 3

  # Footer
  [[menu.footer]]
    url = "https://github.com/gagarine"
    name = "GitHub"
    weight = 1
  [[menu.footer]]
    url = "https://twitter.com/gagarine"
    name = "Twitter"
    weight = 2
  [[menu.footer]]
    url = "https://www.linkedin.com/in/simonperdrisat/"
    name = "Linkedin"
    weight = 3

